project.name = '{{cookiecutter.app_name}}'

application_for :ios, '{{cookiecutter.deployment_target}}' do |target|
  target.name = '{{cookiecutter.app_name}}'
  target.all_configurations.each do |config|
    config.product_bundle_identifier = 'com.{{cookiecutter.company_name|lower}}.{{cookiecutter.app_name|lower}}'
  end

  unit_tests_for target

  rswift_file = '$SRCROOT/{{cookiecutter.app_name}}/Supporting Files/R.generated.swift'
  rswift_generate_script = <<-GENERATE
  "${PODS_ROOT}/R.swift/rswift" generate "#{rswift_file}"
  GENERATE
  target.pre_shell_script_build_phase('R.swift generate', rswift_generate_script) do |phase|
    phase.input_paths = ['$TEMP_DIR/rswift-lastrun']
    phase.output_paths = [rswift_file]
  end
end

project.after_save do
  system "rm -rf \"#{project.name}.xcodeproj/xcshareddata/xcschemes\""
end
